openapi: 3.0.0

info:
  title: Django Files
  description: |
    Django Files: [https://github.com/django-files/django-files](https://github.com/django-files/django-files)
  version: 0.7.0

servers:
  - url: https://intranet.cssnr.com/api
    description: Intranet
  - url: https://f-dev.cssnr.com/api
    description: Development
  - url: https://f.cssnr.com/api
    description: Production


paths:
  /upload:
    post:
      summary: Upload a File
      description: Upload a file to the server with optional parameters.
      tags:
        - Main
      security:
        - Authorization: []

      parameters:
        - name: format
          in: header
          description: File Name Format
          required: false
          schema:
            type: string
        - name: expr
          in: header
          description: File Expiration
          required: false
          schema:
            type: string

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                info:
                  type: string

      responses:
        '200':
          description: A JSON array of file details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileUpload'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'


  /remote/:
    post:
      summary: Upload a Remote URL
      description: Send a URL to a File to Upload.
      tags:
        - Main
      security:
        - Authorization: []

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/URL'
            example:
              url: http://example.com/images/john.png

      responses:
        '200':
          description: A JSON array of file details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'


  /shorten:
    post:
      summary: Shorten a URL
      description: Shorten a URL using header parameters or a JSON encoded body.
      tags:
        - Main
      security:
        - Authorization: []

      parameters:
        - name: url
          in: header
          description: URL to Shorten
          required: false
          schema:
            type: string
        - name: vanity
          in: header
          description: Vanity Name for URL
          required: false
          schema:
            type: string
        - name: max-views
          in: header
          description: Max URL Views
          required: false
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortURL'
            example:
              url: http://example.com/really-long-url.html

      responses:
        '200':
          description: A JSON array of the Short URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URL'
              example:
                url: http://example.com/s/ab12
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/UnauthorizedError'


components:
  securitySchemes:
    Authorization:
      type: apiKey
      in: header
      name: Authorization


  responses:
    BadRequest:
      description: Missing required or malformed parameter
    UnauthorizedError:
      description: Access token is missing or invalid


  schemas:
    URL:
      type: object
      properties:
        url:
          type: string
          example: http://example.com/u/john.png

    ShortURL:
      type: object
      properties:
        url:
          type: string
          example: http://example.com/s/ab12
        vanity:
          type: string
          example: ab12
        max-views:
          type: string
          example: 1

    FileUpload:
      type: object
      properties:
        files:
          type: array
          items:
            type: string
            example: http://example.com/u/john.jpg
        url:
          type: string
          example: http://example.com/u/john.jpg
        raw:
          type: string
          example: http://example.com/r/john.jpg
        name:
          type: string
          example: john.jpg
        size:
          type: integer
          format: int64
          example: 1000


security:
  - Authorization: []
