version: '3.7'

services:
  django-files:
    image: ghcr.io/django-files/django-files:latest
#    env_file: .env
    environment:
      SECRET: "JYGTKLztZxVdu5NXuhXGaSkLJosiiQyBhFJ4LAHrJ5YHigQqq7"
      USERNAME: "testuser"
      PASSWORD: "demopassword"
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.STACK_NAME-http.rule=Host(${TRAEFIK_HOST:-``})"
        - "traefik.http.routers.STACK_NAME-http.entrypoints=http"
        - "traefik.http.routers.STACK_NAME-http.middlewares=https-redirect"
        - "traefik.http.routers.STACK_NAME-https.rule=Host(${TRAEFIK_HOST:-``})"
        - "traefik.http.routers.STACK_NAME-https.entrypoints=https"
        - "traefik.http.routers.STACK_NAME-https.tls=true"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.port=80"
        - "traefik.http.services.STACK_NAME.loadbalancer.server.scheme=http"
    volumes:
      - media_dir:/data/media
      #- logs_dir:/logs
    ports:
      - "80:80"
    #networks:
    #  - traefik-public
    #  - net-internal

#networks:
#  traefik-public:
#    external: true

volumes:
  media_dir:
  #logs_dir:
