# Black

[tool.black]
line-length = 119
extend-exclude = "(\\.github)"

# Ruff

[tool.ruff]
line-length = 119
target-version = "py313"
exclude = [".github"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "B", "Q"]

# Coverage

[tool.coverage.run]
omit = ["*.egg-info/*", ".github/*"]
source = ["src"]

# Isort

[tool.isort]
profile = "black"
lines_after_imports = 2
src_paths = ["src", "test"]
skip = [".github"]
