sonar.python.version=3.14
sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/test_*.py
sonar.issue.ignore.multicriteria.e2.ruleKey=javascript:S2068
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.js
