from api import views
from django.urls import path, re_path
from oauth.views import oauth_show

app_name = "api"

urlpatterns = [
    path("", views.api_view, name="status"),
    re_path(r"^version/?$", views.version_view, name="version"),
    re_path(r"^upload/?$", views.upload_view, name="upload"),
    re_path(r"^shorten/?$", views.shorten_view, name="shorten"),
    path("invites/", views.invites_view, name="invites"),
    path("invites/<int:invite_id>/", views.invite_detail_view, name="invite-detail"),
    path("recent/", views.recent_view, name="recent"),
    path("shorts/", views.shorts_view, name="shorts"),
    path("shorts/<int:page>/", views.shorts_paginated_view, name="shorts-page"),
    path("shorts/<int:page>/<int:count>/", views.shorts_paginated_view, name="shorts-amount"),
    path("shorts/delete/", views.shorts_delete_view, name="shorts-delete"),
    path("users/", views.users_view, name="users"),
    path("users/<int:page>/", views.users_paginated_view, name="users-page"),
    path("users/<int:page>/<int:count>/", views.users_paginated_view, name="users-amount"),
    path("user/", views.user_view, name="current-user"),
    path("user/<int:user_id>/", views.user_view, name="user"),
    path("files/edit/", views.files_edit_view, name="files-edit"),
    path("files/delete/", views.files_edit_view, name="files-delete"),
    path("files/<int:page>/", views.files_view, name="files"),
    path("files/<int:page>/<int:count>/", views.files_view, name="files-amount"),
    path("album/", views.album_view, name="album"),
    path("album/<int:album_id>", views.album_view, name="album-id"),
    path("albums/", views.albums_view, name="albums"),
    path("albums/<int:page>/", views.albums_view, name="albums"),
    path("albums/<int:page>/<int:count>/", views.albums_view, name="albums-amount"),
    path("streams/", views.streams_view, name="streams"),
    path("streams/<int:page>/", views.streams_view, name="streams"),
    path("streams/<int:page>/<int:count>/", views.streams_view, name="streams-amount"),
    path("random/album/<str:user_album>/", views.random_album, name="random-album"),
    path("random/album/<str:user_album>/<path:idname>/", views.random_album, name="random-user-album"),
    path("remote/", views.remote_view, name="remote"),
    path("stats/me/", views.stats_me_view, name="stats-me"),
    path("stats/server/", views.stats_server_view, name="stats-server"),
    path("file/<path:idname>", views.file_view, name="file"),
    path("delete/<path:idname>", views.file_view, name="delete"),
    path("token/", views.token_view, name="token"),
    path("token/<uuid:pk>/", views.token_detail_view, name="token-detail"),
    path("auth/methods/", views.auth_methods, name="auth-methods"),
    path("auth/token/", views.local_auth_for_native_client, name="auth-token"),
    path("auth/session/", views.auth_session, name="auth-session"),
    path("auth/application/", views.auth_application, name="auth-application"),
    path("session/<path:sessionid>", views.session_view, name="session"),
    path("stream/auth/", views.stream_auth_view, name="stream-auth"),
    path("stream/ingest/", views.stream_ingest_view, name="stream-ingest"),
    path("stream/done/", views.stream_done_view, name="stream-done"),
    path("stream/create/", views.stream_create_view, name="stream-create"),
    path("stream/<str:name>/rotate-token/", views.stream_rotate_token_view, name="stream-rotate-token"),
    path("stream/ping/<str:name>/", views.stream_ping_view, name="stream-ping"),
    path("stream/viewers/<str:name>/", views.stream_viewers_view, name="stream-viewers"),
    path("stream/subscribers/<str:name>/", views.stream_subscribers_view, name="stream-subscribers"),
    path("stream/commands/<str:name>/", views.stream_commands_view, name="stream-commands"),
    path("stream/<str:name>/", views.stream_detail_view, name="stream-detail"),
    path("oauth/", oauth_show, name="oauth-show"),
]
