# Generated by Django 4.2.4 on 2023-08-03 09:05

from django.db import migrations, models
import oauth.models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="nav_color_1",
            field=models.CharField(default="#130e36", max_length=7),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nav_color_2",
            field=models.CharField(default="#1e1c21", max_length=7),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_color",
            field=models.CharField(default=oauth.models.rand_color_hex, max_length=7),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="default_expire",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
