# Generated by Django 4.2.4 on 2023-08-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0003_customuser_remove_exif_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remove_exif',
            field=models.BooleanField(default=False, help_text='Removes exif data from images on upload.', verbose_name='No EXIF'),
        ),
    ]
