# Generated by Django 4.2.4 on 2023-09-04 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0005_rename_avatar_hash_customuser_discord_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discord",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("id", models.IntegerField()),
                ("profile", models.JSONField(blank=True, null=True)),
                ("avatar", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "refresh_token",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("expires_in", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Github",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("id", models.IntegerField()),
                ("profile", models.JSONField(blank=True, null=True)),
                ("avatar", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "access_token",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="access_token",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="discord_avatar",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="expires_in",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="oauth_id",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="refresh_token",
        ),
    ]
