# Generated by Django 4.2.4 on 2023-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0006_discord_github_remove_customuser_access_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="show_setup",
            field=models.BooleanField(default=False),
        ),
    ]
