# Generated by Django 4.2.4 on 2023-09-07 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0007_customuser_show_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordWebhooks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(unique=True, verbose_name="Webhook URL")),
                ("hook_id", models.CharField(blank=True, max_length=32, null=True)),
                ("guild_id", models.CharField(blank=True, max_length=32, null=True)),
                ("channel_id", models.CharField(blank=True, max_length=32, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Hook Created Date.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Hook Updated Date.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "DiscordWebhooks",
                "verbose_name_plural": "DiscordWebhooks",
                "ordering": ["-created_at"],
            },
        ),
    ]
