# Generated by Django 4.2.3 on 2023-09-08 02:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0009_alter_discord_options_alter_discordwebhooks_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_upload_name_format",
            field=models.CharField(
                choices=[
                    ("name", "name"),
                    ("rand", "random"),
                    ("date", "date"),
                    ("uuid", "uuid"),
                ],
                default="name",
                max_length=4,
            ),
        ),
    ]
