# Generated by Django 4.2.3 on 2023-09-09 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0012_alter_customuser_show_exif_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_file_private",
            field=models.BooleanField(
                default=False,
                help_text="If enabled file default to private when not specified.",
                verbose_name="Default File Private",
            ),
        ),
    ]
