# Generated by Django 4.2.3 on 2023-09-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0013_customuser_default_file_private"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="default_file_password",
            field=models.BooleanField(
                default=False,
                help_text="Generates file password on upload.",
                verbose_name="Auto File Password",
            ),
        ),
    ]
