# Generated by Django 4.2.5 on 2023-10-05 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0014_customuser_default_file_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="show_setup",
        ),
    ]
