# Generated by Django 4.2.5 on 2023-10-15 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0015_remove_customuser_show_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserBackups",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "filename",
                    models.CharField(max_length=64, verbose_name="Backup File Name"),
                ),
                ("finished", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Backup Created Date.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Backup Updated Date.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
