# Generated by Django 4.2.5 on 2023-10-16 03:52

from django.db import migrations, models
import home.util.storage


class Migration(migrations.Migration):
    dependencies = [
        ("oauth", "0016_userbackups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbackups",
            name="filename",
        ),
        migrations.AddField(
            model_name="userbackups",
            name="file",
            field=home.util.storage.StoragesRouterFileField(
                blank=True, null=True, upload_to="."
            ),
        ),
        migrations.AlterField(
            model_name="userbackups",
            name="finished",
            field=models.BooleanField(default=False, verbose_name="Backup Completed."),
        ),
    ]
