# Generated by Django 4.2.7 on 2024-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0016_customuser_user_avatar_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage_quota',
            field=models.PositiveBigIntegerField(default=0, help_text="User's storage quota in megabytes."),
        ),
        migrations.AddField(
            model_name='customuser',
            name='storage_usage',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
