# Generated by Django 4.2.7 on 2024-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0017_customuser_storage_quota_customuser_storage_usage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='storage_usage',
            field=models.PositiveBigIntegerField(default=0, help_text='Total storage used by user in megabytes.'),
        ),
    ]
