# Generated by Django 5.2.15 on 2026-06-19 15:20

import hashlib
import hmac
import secrets
import string

import oauth.models
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

_TOKEN_ALPHABET = string.ascii_uppercase + string.ascii_lowercase + string.digits


def _migrate_tokens(apps, schema_editor):
    """
    Existing tokens are plaintext and cannot be hashed without the plaintext.
    Invalidate every existing token by replacing it with a fresh HMAC hash that
    nobody knows the plaintext for.  All clients must re-authenticate after this
    migration runs.
    """
    CustomUser = apps.get_model("oauth", "CustomUser")
    now = timezone.now()
    batch = []
    for user in CustomUser.objects.all():
        plaintext = "".join(secrets.choice(_TOKEN_ALPHABET) for _ in range(32))
        digest = hmac.new(
            settings.SECRET_KEY.encode(),
            plaintext.encode(),
            hashlib.sha256,
        ).hexdigest()
        user.authorization = digest
        user.authorization_updated_at = now
        batch.append(user)
    CustomUser.objects.bulk_update(batch, ["authorization", "authorization_updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0024_alter_discord_access_token_alter_discord_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="authorization_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="authorization",
            field=models.CharField(default=oauth.models._default_authorization, max_length=64),
        ),
        migrations.RunPython(_migrate_tokens, migrations.RunPython.noop),
    ]
