# Generated by Django 5.2.15 on 2026-06-19 15:20

import hashlib
import hmac
import uuid

from django.conf import settings
from django.db import migrations, models


def migrate_existing_tokens(apps, schema_editor):
    """
    Migrate existing authorization tokens to ApiToken model.
    Each user's existing plaintext authorization value is hashed and inserted
    as a single ApiToken row. created_at is back-dated to user.date_joined
    via a follow-up update because auto_now_add prevents setting it in bulk_create.
    """
    CustomUser = apps.get_model("oauth", "CustomUser")
    ApiToken = apps.get_model("oauth", "ApiToken")
    users = list(CustomUser.objects.exclude(authorization="").select_related())
    batch = []
    for user in users:
        plaintext = user.authorization  # still plaintext at migration time
        digest = hmac.new(
            settings.SECRET_KEY.encode(),
            plaintext.encode(),
            hashlib.sha256,
        ).hexdigest()
        batch.append(
            ApiToken(
                user=user,
                token_hash=digest,
                name="Migrated Token",
                user_agent="Migrated Legacy Token",
            )
        )
    ApiToken.objects.bulk_create(batch, ignore_conflicts=True)
    # Back-date created_at to each user's join date; auto_now_add blocks this above.
    for user in users:
        ApiToken.objects.filter(user=user, name="Migrated Token").update(created_at=user.date_joined)


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0024_alter_discord_access_token_alter_discord_avatar_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="api_tokens",
                        to="oauth.customuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RunPython(migrate_existing_tokens, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="customuser",
            name="authorization",
        ),
    ]
