# Generated by Django 5.2.15 on 2026-06-26 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0025_apitoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="PasskeyCredential",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "credential_id",
                    models.CharField(db_index=True, help_text="Base64url credential id.", max_length=512, unique=True),
                ),
                ("public_key", models.TextField(help_text="Base64url COSE public key.")),
                ("sign_count", models.PositiveBigIntegerField(default=0)),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="User supplied label, e.g. 'MacBook Touch ID'.", max_length=200
                    ),
                ),
                ("transports", models.JSONField(blank=True, default=list, help_text="Authenticator transports hint.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, help_text="User agent string from when the passkey was registered.", max_length=500
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passkeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Passkey",
                "verbose_name_plural": "Passkeys",
                "ordering": ["-created_at"],
            },
        ),
    ]
