# Generated by Django 5.2.15 on 2026-07-10 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth", "0026_passkeycredential"),
        # the data migration must copy legacy rows before the table is dropped
        ("home", "0038_migrate_discord_webhooks"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscordWebhooks",
        ),
    ]
