# Generated by Django 5.1.11 on 2025-07-30 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Group",
                "verbose_name_plural": "Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionInfo",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("browser", models.CharField(max_length=100, verbose_name="Browser")),
                ("user_agent", models.CharField(blank=True, max_length=500, verbose_name="User Agent")),
                ("endpoint", models.URLField(max_length=500, verbose_name="Endpoint")),
                ("auth", models.CharField(max_length=100, verbose_name="Auth")),
                ("p256dh", models.CharField(max_length=100, verbose_name="P256DH")),
            ],
            options={
                "verbose_name": "Subscription Info",
                "verbose_name_plural": "Subscription Infos",
                "ordering": ["browser"],
            },
        ),
        migrations.CreateModel(
            name="PushInformation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webpush_info",
                        to="webpush.group",
                        verbose_name="Group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webpush_info",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webpush_info",
                        to="webpush.subscriptioninfo",
                        verbose_name="Subscription",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Information",
                "verbose_name_plural": "Push Information",
                "ordering": ["user", "group"],
            },
        ),
    ]
