# Generated by Django 4.2.4 on 2023-09-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="initial_setup",
            field=models.BooleanField(default=False),
        ),
    ]
