# Generated by Django 4.2.4 on 2023-09-07 00:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_remove_sitesettings_initial_setup"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Webhooks",
        ),
    ]
