# Generated by Django 4.2.5 on 2023-09-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_delete_webhooks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="latest_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discord_client_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="discord_client_secret",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="github_client_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="github_client_secret",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="s3_bucket_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="s3_cdn",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Replaces s3 hostname on urls to allow cdn use in front of s3 bucket.",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="s3_region",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="s3_secret_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="s3_secret_key_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
