# Generated by Django 4.2.5 on 2023-09-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0006_alter_sitesettings_discord_client_id_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "verbose_name": "Site Setting",
                "verbose_name_plural": "Site Settings",
            },
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="latest_version",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
