# Generated by Django 4.2.7 on 2024-04-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_sitesettings_show_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_user_storage_quota',
            field=models.PositiveBigIntegerField(default=0, help_text='Default storage capacity for new users in megabytes.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_storage_quota',
            field=models.PositiveBigIntegerField(default=0, help_text='Total storage capacity for entire django files deployment in megabytes.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='global_storage_usage',
            field=models.PositiveBigIntegerField(default=0, help_text='Current global storage usage in megabytes.'),
        ),
    ]
