# Generated by Django 4.2.7 on 2024-04-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_sitesettings_default_user_storage_quota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='default_user_storage_quota',
            field=models.PositiveBigIntegerField(default=0, help_text='Default storage capacity for new users in bytes.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='global_storage_quota',
            field=models.PositiveBigIntegerField(default=0, help_text='Total storage capacity for entire django files deployment in bytes.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='global_storage_usage',
            field=models.PositiveBigIntegerField(default=0, help_text='Current global storage usage in bytes.'),
        ),
    ]
