# Generated by Django 4.2.11 on 2024-05-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_alter_sitesettings_default_user_storage_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='google_client_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_client_secret',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
