# Generated by Django 4.2.11 on 2024-05-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_sitesettings_google_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='local_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_client_id',
            field=models.CharField(blank=True, default='', max_length=75),
        ),
    ]
