# Generated by Django 4.2.5 on 2024-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0011_sitesettings_local_auth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="login_background",
            field=models.CharField(default="video", max_length=16),
        ),
    ]
