# Generated by Django 4.2.5 on 2024-07-10 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0012_sitesettings_background_picture_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_animations",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tsparticles_config",
            field=models.CharField(
                default="/static/config/tsparticles.json", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tsparticles_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
