# Generated by Django 4.2.5 on 2024-06-23 03:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0013_sitesettings_background_picture_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="background_video",
            field=models.CharField(default="video/loop.mp4", max_length=255),
        ),
    ]
