# Generated by Django 5.1.6 on 2025-05-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0014_alter_sitesettings_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="pub_album",
            field=models.IntegerField(default=0, help_text="Public Upload Album", verbose_name="Public Album"),
        ),
    ]
