# Generated by Django 4.2.5 on 2024-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0014_alter_sitesettings_background_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="background_video",
            field=models.CharField(default="/static/video/loop.mp4", max_length=255),
        ),
    ]
