# Generated by Django 5.1.11 on 2025-07-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0015_sitesettings_pub_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="VAPIDKeys",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public", models.CharField(max_length=255)),
                ("private", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
