# Generated by Django 5.2.15 on 2026-06-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0016_vapidkeys"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="passkey_auth",
            field=models.BooleanField(
                default=True, help_text="Allow passkey (WebAuthn) login and registration", verbose_name="Passkeys"
            ),
        ),
    ]
