# Generated by Django 5.2.15 on 2026-09-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0017_sitesettings_passkey_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="per_album_public_uploads",
            field=models.BooleanField(
                default=False,
                help_text="Allow album owners to enable a public, unauthenticated upload link for their own albums.",
                verbose_name="Per-Album Public Uploads",
            ),
        ),
    ]
