# Generated by Django 4.2.4 on 2023-08-02 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Files",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.FileField(upload_to=".")),
                (
                    "size",
                    models.IntegerField(
                        default=0,
                        help_text="File Size in Bytes.",
                        verbose_name="File Size",
                    ),
                ),
                (
                    "mime",
                    models.CharField(
                        blank=True,
                        help_text="File MIME Type.",
                        max_length=255,
                        null=True,
                        verbose_name="File MIME",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="File Name Basename.",
                        max_length=255,
                        null=True,
                        verbose_name="File Name",
                    ),
                ),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        help_text="File Information.",
                        max_length=255,
                        null=True,
                        verbose_name="File Info",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="File Created Date.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "edit",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="File Edited Date.",
                        verbose_name="Date Edited",
                    ),
                ),
                (
                    "expr",
                    models.CharField(
                        default="",
                        help_text="File Expire Time.",
                        max_length=32,
                        verbose_name="Expire Time",
                    ),
                ),
            ],
            options={
                "verbose_name": "Files",
                "verbose_name_plural": "Files",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "site_url",
                    models.URLField(
                        max_length=128, unique=True, verbose_name="Site URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.CreateModel(
            name="Webhooks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(unique=True, verbose_name="Webhook URL")),
                ("hook_id", models.CharField(blank=True, max_length=32, null=True)),
                ("guild_id", models.CharField(blank=True, max_length=32, null=True)),
                ("channel_id", models.CharField(blank=True, max_length=32, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Hook Created Date.",
                        verbose_name="Date Created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Hook Edited Date.",
                        verbose_name="Date Edited",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
            },
        ),
    ]
