# Generated by Django 4.2.4 on 2023-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="expr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File Expire Time.",
                max_length=32,
                verbose_name="Expire Time",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_url",
            field=models.URLField(
                default="https://intranet.cssnr.com",
                max_length=128,
                verbose_name="Site URL",
            ),
        ),
    ]
