# Generated by Django 4.2.4 on 2023-08-05 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0003_alter_files_expr_alter_sitesettings_site_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="webhooks",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
            },
        ),
        migrations.CreateModel(
            name="FileStats",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("stats", models.JSONField(verbose_name="Stats JSON")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Stats Created Date.",
                        verbose_name="Stats Created",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "FileStats",
                "verbose_name_plural": "FileStats",
                "ordering": ["-created_at"],
            },
        ),
    ]
