# Generated by Django 4.2.4 on 2023-08-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_webhooks_options_filestats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(default='https://example.com', max_length=128, verbose_name='Site URL'),
        ),
    ]
