# Generated by Django 4.2.4 on 2023-08-05 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("home", "0004_alter_webhooks_options_filestats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="files",
            options={
                "ordering": ["-date"],
                "verbose_name": "File",
                "verbose_name_plural": "Files",
            },
        ),
        migrations.AlterModelOptions(
            name="filestats",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "FileStat",
                "verbose_name_plural": "FileStats",
            },
        ),
        migrations.AlterModelOptions(
            name="sitesettings",
            options={"verbose_name": "Setting", "verbose_name_plural": "Settings"},
        ),
        migrations.AlterField(
            model_name="files",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="File Created Date.",
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="edit",
            field=models.DateTimeField(
                auto_now=True, help_text="File Edited Date.", verbose_name="Edited"
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="expr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File Expire.",
                max_length=32,
                verbose_name="Expiration",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="info",
            field=models.CharField(
                blank=True,
                help_text="File Information.",
                max_length=255,
                null=True,
                verbose_name="Info",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="mime",
            field=models.CharField(
                blank=True,
                help_text="File MIME Type.",
                max_length=255,
                null=True,
                verbose_name="MIME",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="File Name.",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="size",
            field=models.IntegerField(
                default=0, help_text="File Size in Bytes.", verbose_name="Size"
            ),
        ),
        migrations.AlterField(
            model_name="filestats",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Stats Updated Date.",
                verbose_name="Updated",
            ),
        ),
        migrations.AlterField(
            model_name="filestats",
            name="stats",
            field=models.JSONField(
                help_text="Stats JSON Data.", verbose_name="Stats JSON"
            ),
        ),
        migrations.AlterField(
            model_name="webhooks",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Hook Created Date.",
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="webhooks",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Hook Updated Date.", verbose_name="Updated"
            ),
        ),
        migrations.CreateModel(
            name="ShortURLs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "short",
                    models.CharField(
                        help_text="Short Link ID.",
                        max_length=255,
                        unique=True,
                        verbose_name="Short",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Target URL for the ShortURL.",
                        verbose_name="Destination URL",
                    ),
                ),
                (
                    "max",
                    models.IntegerField(
                        default=0, help_text="Max ShortURL Views", verbose_name="Max"
                    ),
                ),
                (
                    "views",
                    models.IntegerField(
                        default=0,
                        help_text="Total ShortURL Views",
                        verbose_name="Views",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="ShortURL Created Date.",
                        verbose_name="Created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="ShortURL Updated Date.",
                        verbose_name="Updated",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Short URL",
                "verbose_name_plural": "Short URLs",
                "ordering": ["-created_at"],
            },
        ),
    ]
