# Generated by Django 4.2.4 on 2023-08-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_files_options_alter_filestats_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturls",
            name="short",
            field=models.CharField(
                default="migrate-test",
                help_text="ShortURL Short URL.",
                max_length=255,
                unique=True,
                verbose_name="ShortURL Short",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shorturls",
            name="url",
            field=models.URLField(
                help_text="ShortURL Destination URL.", verbose_name="ShortURL URL"
            ),
        ),
    ]
