# Generated by Django 4.2.4 on 2023-08-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_shorturls_short_alter_shorturls_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="File Created Date.",
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="edit",
            field=models.DateTimeField(
                auto_now=True, help_text="File Edited Date.", verbose_name="Edited"
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="expr",
            field=models.CharField(
                blank=True,
                default="",
                help_text="File Expire.",
                max_length=32,
                verbose_name="Expiration",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="info",
            field=models.CharField(
                blank=True,
                help_text="File Information.",
                max_length=255,
                null=True,
                verbose_name="Info",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="mime",
            field=models.CharField(
                blank=True,
                help_text="File MIME Type.",
                max_length=255,
                null=True,
                verbose_name="MIME",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="File Name Basename.",
                max_length=255,
                null=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="files",
            name="size",
            field=models.IntegerField(
                default=0, help_text="File Size in Bytes.", verbose_name="Size"
            ),
        ),
        migrations.AlterField(
            model_name="filestats",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Stats Updated Date.",
                verbose_name="Updated",
            ),
        ),
        migrations.AlterField(
            model_name="filestats",
            name="stats",
            field=models.JSONField(
                help_text="Stats JSON Data.", verbose_name="Stats JSON"
            ),
        ),
        migrations.AlterField(
            model_name="shorturls",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="ShortURL Created Date.",
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="shorturls",
            name="short",
            field=models.CharField(
                help_text="Short Link ID.",
                max_length=255,
                unique=True,
                verbose_name="Short",
            ),
        ),
        migrations.AlterField(
            model_name="shorturls",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="ShortURL Updated Date.",
                verbose_name="Updated",
            ),
        ),
        migrations.AlterField(
            model_name="shorturls",
            name="url",
            field=models.URLField(
                help_text="Target URL for the ShortURL.", verbose_name="Destination URL"
            ),
        ),
        migrations.AlterField(
            model_name="shorturls",
            name="views",
            field=models.IntegerField(
                default=0, help_text="Max ShortURL Views", verbose_name="Max Views"
            ),
        ),
        migrations.AlterField(
            model_name="webhooks",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Hook Created Date.",
                verbose_name="Created",
            ),
        ),
        migrations.AlterField(
            model_name="webhooks",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Hook Updated Date.", verbose_name="Updated"
            ),
        ),
    ]
