# Generated by Django 4.2.4 on 2023-08-07 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0009_alter_files_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="exif",
            field=models.JSONField(
                default={},
                help_text="JSON formatted exif metadata.",
                verbose_name="EXIF Metadata",
            ),
        ),
    ]
