# Generated by Django 4.2.4 on 2023-08-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0010_files_exif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="exif",
            field=models.JSONField(
                default=dict,
                help_text="JSON formatted exif metadata.",
                verbose_name="EXIF Metadata",
            ),
        ),
    ]
