# Generated by Django 4.2.4 on 2023-08-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0011_alter_files_exif"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestats",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Stats Updated Date.", verbose_name="Updated"
            ),
        ),
        migrations.AlterField(
            model_name="filestats",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Stats Updated Date.",
                verbose_name="Created",
            ),
        ),
    ]
