# Generated by Django 4.2.4 on 2023-08-10 03:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0012_filestats_updated_at_alter_filestats_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="maxv",
            field=models.IntegerField(
                default=0, help_text="Max Views.", verbose_name="Max"
            ),
        ),
        migrations.AddField(
            model_name="files",
            name="view",
            field=models.IntegerField(
                default=0, help_text="File Views.", verbose_name="Views"
            ),
        ),
    ]
