# Generated by Django 4.2.3 on 2023-08-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0013_files_maxv_files_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="meta",
            field=models.JSONField(
                default=dict,
                help_text="JSON formatted metadata.",
                verbose_name="Metadata",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_url",
            field=models.URLField(
                default="https://example.com", max_length=128, verbose_name="Site URL"
            ),
        ),
    ]
