# Generated by Django 4.2.4 on 2023-08-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0014_files_meta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="site_url",
            field=models.URLField(
                blank=True, max_length=128, null=True, verbose_name="Site URL"
            ),
        ),
    ]
