# Generated by Django 4.2.3 on 2023-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0015_alter_sitesettings_site_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="s3_bucket_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="s3_cdn",
            field=models.CharField(
                blank=True,
                help_text="Replaces s3 hostname on urls to allow cdn use in front of s3 bucket.",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="s3_region",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="s3_secret_key",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="s3_secret_key_id",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
