# Generated by Django 4.2.4 on 2023-08-23 04:21

from django.db import migrations
import home.util.storage


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0016_sitesettings_s3_bucket_name_sitesettings_s3_cdn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="files",
            name="file",
            field=home.util.storage.StoragesRouterFileField(upload_to="."),
        ),
    ]
