# Generated by Django 4.2.4 on 2023-08-29 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0017_alter_files_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="oauth_reg",
            field=models.BooleanField(
                default=False,
                help_text="Allow Oauth Auto Registration",
                verbose_name="Oauth Reg",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="two_factor",
            field=models.BooleanField(
                default=False,
                help_text="Require Two-Factor Authentication",
                verbose_name="Two-Factor",
            ),
        ),
    ]
