# Generated by Django 4.2.3 on 2023-09-02 02:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_sitesettings_oauth_reg_sitesettings_two_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Site Title"
            ),
        ),
    ]
