# Generated by Django 4.2.4 on 2023-09-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0018_sitesettings_oauth_reg_sitesettings_two_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="duo_auth",
            field=models.BooleanField(
                default=False,
                help_text="Require Duo Authentication",
                verbose_name="Duo AUth",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pub_load",
            field=models.BooleanField(
                default=False,
                help_text="Allow Public Uploads",
                verbose_name="Public Upload",
            ),
        ),
    ]
