# Generated by Django 4.2.4 on 2023-09-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0019_sitesettings_site_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="duo_auth",
            field=models.BooleanField(
                default=False,
                help_text="Require Duo Authentication",
                verbose_name="Duo AUth",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="pub_load",
            field=models.BooleanField(
                default=False,
                help_text="Allow Public Uploads",
                verbose_name="Public Upload",
            ),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="site_title",
            field=models.CharField(
                default="Django Files", max_length=64, verbose_name="Site Title"
            ),
        ),
    ]
