# Generated by Django 4.2.3 on 2023-09-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0020_sitesettings_duo_auth_sitesettings_pub_load_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="File Password"
            ),
        ),
    ]
