# Generated by Django 4.2.4 on 2023-09-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_files_password_files_private_alter_files_exif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="discord_client_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="discord_client_secret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="github_client_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="github_client_secret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="oauth_redirect_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
