# Generated by Django 4.2.4 on 2023-09-05 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0021_files_password_files_private_alter_files_exif_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sitesettings",
            old_name="s3_secret_key_id",
            new_name="aws_access_key_id",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="s3_region",
            new_name="aws_region_name",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="s3_secret_key",
            new_name="aws_secret_access_key",
        ),
        migrations.RenameField(
            model_name="sitesettings",
            old_name="s3_bucket_name",
            new_name="aws_storage_bucket_name",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="aws_querystring_expire",
            field=models.IntegerField(blank=True, default=3600, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="aws_s3_cdn_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="discord_client_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="discord_client_secret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="github_client_id",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="github_client_secret",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="oauth_redirect_url",
            field=models.URLField(blank=True, max_length=128, null=True),
        ),
    ]
