# Generated by Django 4.2.4 on 2023-09-05 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0022_sitesettings_discord_client_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SiteSettings",
        ),
        migrations.DeleteModel(
            name="Webhooks",
        ),
    ]
