# Generated by Django 4.2.3 on 2023-09-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0023_delete_sitesettings_delete_webhooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="meta_preview",
            field=models.BooleanField(
                default=True, help_text="Show metadata on previews."
            ),
        ),
    ]
