# Generated by Django 4.2.7 on 2024-03-31 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_files_meta_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='avatar',
            field=models.BooleanField(default=False, help_text='Determines file is a user avatar.'),
        ),
    ]
