# Generated by Django 4.2.11 on 2024-04-14 15:49

from django.db import migrations
import home.util.storage


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_files_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='thumb',
            field=home.util.storage.StoragesRouterFileField(null=True, upload_to='./.thumbs/'),
        ),
    ]
