# Generated by Django 4.2.11 on 2024-05-28 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_files_thumb_albums_files_albums'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albums',
            options={'ordering': ['-date'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
    ]
