# Generated by Django 4.2.11 on 2024-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_files_thumb_albums_files_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='maxv',
            field=models.IntegerField(default=0, help_text='Max Views.', verbose_name='Max'),
        ),
        migrations.AddField(
            model_name='albums',
            name='view',
            field=models.IntegerField(default=0, help_text='Album Views.', verbose_name='Views'),
        ),
    ]
