# Generated by Django 4.2.5 on 2024-06-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0028_alter_albums_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albums",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Album Name.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Name",
            ),
        ),
    ]
