# Generated by Django 4.2.11 on 2024-05-27 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_albums_maxv_albums_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Album Created Date.', verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albums',
            name='expr',
            field=models.CharField(blank=True, default='', help_text='Album Expire.', max_length=32, verbose_name='Expiration'),
        ),
    ]
