# Generated by Django 5.1.7 on 2025-08-10 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_alter_albums_info_alter_albums_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "name",
                    models.CharField(
                        help_text="Stream Name",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                ("title", models.CharField(help_text="Stream Title", max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Stream Description", verbose_name="Description"
                    ),
                ),
                (
                    "isLive",
                    models.BooleanField(default=False, help_text="Stream Live Status", verbose_name="Live Status"),
                ),
                (
                    "startedAt",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Stream Started DateTime", verbose_name="Started At"
                    ),
                ),
                (
                    "endedAt",
                    models.DateTimeField(
                        blank=True, help_text="Stream Ended DateTime", null=True, verbose_name="Ended At"
                    ),
                ),
                (
                    "uniqueViewers",
                    models.IntegerField(
                        default=0, help_text="Unique stream impressions", verbose_name="Unique Viewers"
                    ),
                ),
                (
                    "public",
                    models.BooleanField(default=True, help_text="Stream Public Boolean", verbose_name="Public"),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True, default="", help_text="Stream Password", max_length=255, verbose_name="Password"
                    ),
                ),
                (
                    "viewerLimit",
                    models.IntegerField(default=0, help_text="Max stream viewers", verbose_name="Viewer Limit"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="User"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream",
                "verbose_name_plural": "Streams",
                "ordering": ["-startedAt"],
            },
        ),
        migrations.CreateModel(
            name="StreamDiscordWebhooks",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(unique=True, verbose_name="Webhook URL")),
                ("hook_id", models.CharField(blank=True, max_length=32)),
                ("guild_id", models.CharField(blank=True, max_length=32)),
                ("channel_id", models.CharField(blank=True, max_length=32)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Hook Created Date.", verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Hook Updated Date.", verbose_name="Updated"),
                ),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                (
                    "stream",
                    models.ForeignKey(
                        help_text="Stream Object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.stream",
                        verbose_name="Stream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Webhooks for Streams",
                "verbose_name_plural": "Discord Webhooks for Streams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StreamHistory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "startedAt",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Stream Start Datetime.", verbose_name="Started At"
                    ),
                ),
                (
                    "endedAt",
                    models.DateTimeField(
                        blank=True, help_text="Stream End Datetime.", null=True, verbose_name="Ended At"
                    ),
                ),
                (
                    "peakViewers",
                    models.IntegerField(default=0, help_text="Peak View Count", verbose_name="Peak Viewers"),
                ),
                (
                    "avgViewers",
                    models.IntegerField(default=0, help_text="Average View Count", verbose_name="Average Viewers"),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Stream title at time of recording.",
                        max_length=255,
                        verbose_name="Title",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Stream description at time of recording.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "recording",
                    models.OneToOneField(
                        blank=True,
                        help_text="Link to recording as a file object.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="home.files",
                        verbose_name="Recording",
                    ),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        help_text="Stream Object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.stream",
                        verbose_name="Stream",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream History",
                "verbose_name_plural": "Streams History",
                "ordering": ["-startedAt"],
            },
        ),
    ]
