# Generated by Django 5.2.15 on 2026-07-01 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0034_stream_playback_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tag", models.CharField(max_length=255)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="home.files"
                    ),
                ),
            ],
            options={
                "verbose_name": "File Tag",
                "verbose_name_plural": "File Tags",
                "indexes": [models.Index(fields=["tag"], name="home_fileta_tag_410473_idx")],
                "unique_together": {("file", "tag")},
            },
        ),
    ]
