# Generated by Django 5.2.15 on 2026-07-10 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_filetag_xmp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Webhook Name.", max_length=128, verbose_name="Name")),
                (
                    "webhook_type",
                    models.CharField(
                        choices=[("custom", "Custom"), ("discord", "Discord")],
                        default="custom",
                        max_length=16,
                        verbose_name="Type",
                    ),
                ),
                ("url", models.URLField(verbose_name="Webhook URL")),
                (
                    "secret",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 signing secret for custom hooks.",
                        max_length=128,
                        verbose_name="Secret",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "events",
                    models.JSONField(
                        blank=True, default=list, help_text="Subscribed event keys.", verbose_name="Events"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Hook Created Date.", verbose_name="Created"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Hook Updated Date.", verbose_name="Updated"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
                "ordering": ["-created_at"],
            },
        ),
    ]
