# Generated by Django 5.2.15 on 2026-07-10 17:56

from django.db import migrations, models

SITE_ONLY_EVENTS = {"user.created", "user.deleted"}


def scope_existing_webhooks(apps, schema_editor):
    """Preserve pre-scope behavior.

    Staff-owned hooks subscribed to user.created/user.deleted received those
    events globally, while their other events fired for the owner only. Hooks
    with only site-only events become site-scoped; mixed hooks are split into
    a user hook and a site hook. Site-only events never fired for non-staff
    owners, so they are simply stripped.
    """
    Webhook = apps.get_model("home", "Webhook")
    for webhook in Webhook.objects.all():
        events = webhook.events or []
        site_events = [event for event in events if event in SITE_ONLY_EVENTS]
        if not site_events:
            continue
        user_events = [event for event in events if event not in SITE_ONLY_EVENTS]
        if not webhook.owner.is_staff:
            webhook.events = user_events
            webhook.save(update_fields=["events"])
        elif not user_events:
            webhook.scope = "site"
            webhook.save(update_fields=["scope"])
        else:
            webhook.events = user_events
            webhook.save(update_fields=["events"])
            Webhook.objects.create(
                owner_id=webhook.owner_id,
                name=f"{webhook.name} (site)"[:128],
                webhook_type=webhook.webhook_type,
                scope="site",
                url=webhook.url,
                secret=webhook.secret,
                active=webhook.active,
                events=site_events,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_migrate_discord_webhooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="scope",
            field=models.CharField(
                choices=[("user", "User"), ("site", "Site")],
                default="user",
                help_text="Site-scoped hooks receive events for all users; superuser only.",
                max_length=16,
                verbose_name="Scope",
            ),
        ),
        migrations.RunPython(scope_existing_webhooks, migrations.RunPython.noop),
    ]
