# Generated by Django 5.2.15 on 2026-07-12 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0039_webhook_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="filters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Event filters, e.g. {'tags': ['work', '!private']} to filter file events by tag.",
                verbose_name="Filters",
            ),
        ),
    ]
