# Generated by Django 5.2.15 on 2026-07-12 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0043_tag_finalize"),
    ]

    operations = [
        migrations.CreateModel(
            name="StreamTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tags", to="home.stream"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="stream_tags", to="home.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stream Tag",
                "verbose_name_plural": "Stream Tags",
                "unique_together": {("stream", "tag")},
            },
        ),
    ]
