# Generated by Django 5.2.15 on 2026-07-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0044_streamtag"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="record",
            field=models.BooleanField(
                default=False, help_text="Record this stream and save it as a file.", verbose_name="Record"
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="recording_retention_count",
            field=models.IntegerField(
                blank=True,
                help_text="Keep only this many most recent recordings, deleting older ones. Empty = keep all.",
                null=True,
                verbose_name="Recording Retention Count",
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="recording_retention_days",
            field=models.IntegerField(
                blank=True,
                help_text="Delete recordings older than this many days. Empty = never expire by age.",
                null=True,
                verbose_name="Recording Retention Days",
            ),
        ),
    ]
