# Generated by Django 5.2.15 on 2026-09-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0046_merge_public_into_anonymous"),
    ]

    operations = [
        migrations.AddField(
            model_name="albums",
            name="public_uploads",
            field=models.BooleanField(
                default=False,
                help_text="Allow anonymous visitors to upload files into this album via its upload link.",
                verbose_name="Public Uploads",
            ),
        ),
    ]
