name: Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags: comma,separated'
        required: true
        default: 'latest'

env:
  REGISTRY: "ghcr.io"
  USER: "django-files"
  REPO: "django-files"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Tags"
        id: tags
        run: |
          echo "Input Tags: ${{ inputs.tags }}"
          TAGS=""
          IFS=',' read -ra INPUT <<< "${{ inputs.tags }}"
          for tag in "${INPUT[@]}";do
            echo "${REGISTRY}/${USER}/${REPO}:${tag}"
            TAGS+="${REGISTRY}/${USER}/${REPO}:${tag},"
          done
          TAGS="$(echo ${TAGS} | sed 's/,*$//g')"
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "Parsed Tags: ${TAGS}"

      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Docker Login"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Build and Push"
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
