name: "Build"

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: "Override Tags: comma,separated"
        required: false

env:
  REGISTRY: "ghcr.io"
  USER: "django-files"
  REPO: "django-files"
  PRE_TAG: "prerelease"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 25
    permissions:
      contents: read
      packages: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Docker Tags"
        id: tags
        uses: cssnr/docker-tags-action@v1
        continue-on-error: true
        with:
          tags: |
            ${{ inputs.tags }}
            ${{ github.event.release.prerelease && env.PRE_TAG || '' }}

      - name: "Debug Docker Tags"
        continue-on-error: true
        run: |
          echo inputs.tags: '${{ inputs.tags }}'
          echo -e "tags:\n${{ steps.tags.outputs.tags }}"
          echo -e "labels:\n${{ steps.tags.outputs.labels }}"

      - name: "Setup Buildx"
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: "Docker Login"
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_PASS }}

      - name: "Build and Push"
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.tags.outputs.tags }}
          labels: ${{ steps.tags.outputs.labels }}

      - name: "Send Build Notification"
        if: ${{ always() }}
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
