name: "Lint"

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read

    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Debug event.json"
        continue-on-error: true
        run: cat "${GITHUB_EVENT_PATH}"
      - name: "Debug CTX github"
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"
      - name: "Debug Environment"
        continue-on-error: true
        run: env

      #- name: "Setup Python 3.12"
      #  uses: actions/setup-python@v6
      #  with:
      #    python-version: "3.12"

      - name: "Install UV"
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: "Install Python"
        run: |
          uv python install

      - name: "Install Project"
        run: |
          uv sync --locked --all-extras --dev
          #uv pip install --system -r app/requirements-dev.txt
          uv pip install -r app/requirements-dev.txt

      - name: "Debug UV"
        if: ${{ !cancelled() }}
        continue-on-error: true
        run: |
          uv python dir
          uv python find
          uv run python -V
          echo "::group::uv tree"
          uv tree
          echo "::endgroup::"
          echo "::group::uv pip list"
          uv pip list
          echo "::endgroup::"

      #- name: "flake8"
      #  if: ${{ !cancelled() }}
      #  run: |
      #    flake8 --max-line-length 119 --ignore E203 --extend-exclude "venv,node_modules,migrations" .

      - name: "astral-sh/ruff"
        if: ${{ !cancelled() }}
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        with:
          version: latest

      - name: "astral-sh/ty"
        if: ${{ !cancelled() }}
        continue-on-error: true
        run: |
          uv run ty check -v

      - name: "black"
        if: ${{ !cancelled() }}
        uses: psf/black@stable

      - name: "isort"
        if: ${{ !cancelled() }}
        uses: isort/isort-action@24d8a7a51d33ca7f36c3f23598dafa33f7071326 # v1.1.1

      - name: "mypy"
        if: ${{ !cancelled() }}
        continue-on-error: true
        run: |
          uv run mypy app

      - name: "bandit"
        if: ${{ !cancelled() }}
        run: |
          uv run bandit -c pyproject.toml -r app

      - name: "tombi"
        if: ${{ !cancelled() }}
        run: |
          uv run tombi lint

      - name: "prettier"
        if: ${{ !cancelled() }}
        run: |
          echo "::group::Install"
          npm install prettier
          echo "::endgroup::"
          npx prettier --check .

      - name: "hadolint"
        if: ${{ !cancelled() }}
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: Dockerfile
          recursive: true
          ignore: DL3007,DL3008,DL3009,DL3013,DL3018

      - name: "yamllint"
        if: ${{ !cancelled() }}
        env:
          CONFIG: .github/yamllint.yaml
        run: |
          echo "::group::List Files"
          yamllint -c "${{ env.CONFIG }}" --list-files .
          echo "::endgroup::"
          yamllint -c "${{ env.CONFIG }}" .

      - name: "actionlint"
        if: ${{ !cancelled() }}
        uses: cssnr/actionlint-action@v1

      #- name: "Vale"
      #  if: ${{ !cancelled() }}
      #  uses: errata-ai/vale-action@v2.1.1

      #- name: "SonarQube"
      #  uses: SonarSource/sonarqube-scan-action@v4
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
