name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#noci') }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Dependencies ${{ matrix.version }}"
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          cd app
          pip install -r requirements.txt

      - name: "Flake8"
        run: |
          cd app
          flake8

      - name: "Coverage"
        run: |
          cd app
          coverage run manage.py test
          coverage report
