name: Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#noci') }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Dependencies ${{ matrix.version }}"
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          pip install -r requirements.txt

      - name: "Flake8"
        working-directory: app
        run: |
          flake8

      - name: "Migrate"
        working-directory: app
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: "Coverage"
        working-directory: app
        run: |
          coverage run manage.py test
          coverage report
#          export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_PROJECT_TOKEN }}
#          bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r .coverage

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: app/.coverage
