name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master", "*.*.*"]
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '[CI SKIP]') }}

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: "Requirements ${{ matrix.version }}"
        working-directory: app
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-dev.txt
          playwright install chromium

      - name: "Flake8"
        working-directory: app
        run: |
          flake8

#      - name: "Migrate"
#        working-directory: app
#        run: |
#          python manage.py makemigrations
#          python manage.py migrate

      - name: "Test"
        working-directory: app
        run: |
          coverage run manage.py test --verbosity 2 --keepdb
          coverage xml
          coverage report

      - name: "Codacy Coverage"
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: app/coverage.xml

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: app/screenshots/

      - name: "Push Artifacts"
        uses: hosted-domains/gh-push-artifacts@master
        with:
          path: "app/screenshots/"
          host: ${{ secrets.ARTIFACTS_HOST }}
          user: ${{ secrets.RSYNC_USER }}
          pass: ${{ secrets.RSYNC_PASS }}
          port: ${{ secrets.RSYNC_PORT }}
          base: "/static"
          webhost: "https://artifacts.hosted-domains.com"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
